const messages: { [key: string]: { [key: string]: string } } = {
    en: {
        requiredInput: "All input is required",
        invalidEmail: "Invalid Email",
        invalidPassword: "Invalid Password",
        loginSuccess: "Login successful",
        internalServerError: "Internal server error",
        adminProfileSuccess: "Admin profile get successfully",
        invalidUserId: "User ID is missing or invalid",
        userNotFound: "User not found",
        userUpdated: "User updated successfully",
        oldNewPasswordRequired: "Old and new passwords are required",
        newPasswordSame: "New password cannot be the same as the old password",
        invalidOldPassword: "Invalid old password",
        passwordChanged: "Password changed successfully",
        passwordChangeFailed: "Failed to change password",
        validEmailRequired: "Please enter a valid email",
        otpError: "Error sending OTP",
        otpSent: "OTP sent successfully",
        emailOtpRequired: "email and otp required",
        invalidOtp: "Invalid or expired OTP",
        otpVerified: "OTP verified successfully",
        passwordUpdated: "Password update successfully",
        agentAdded: "Agent added and email sent successfully",
        agencyAdded: "Agency added successfully",
        agencyNotFound: "Agency not found",
        agencyUpdated: "Agency updated successfully",
        agencyDeleted: "Agency deleted successfully",
        customerAdded: "Customer Add Successfully",
        customerUpdated: "Customer updated successfully",
        customerDeleted: "Customer deleted successfully",
        masterDataAdded: "Master Data add successfully",
        masterDataNotFound: "Master data not found",
        masterDataUpdated: "Master data updated successfully",
        masterDataDeleted: "Master data deleted successfully",
        languageUpdated:"Language updated successfully",
        languageRequired:"Language is required",
        jobAdded:"Job added successfully",
        jobNotFound:"Job not found",
        jobUpdated:"Job updated successfully",
        jobget:"job get successfully",
        getjobDetails:"job details get successfully",
        jobDeleted:"job delete successfully",
        jobCompleted:"Job marked as Completed successfully",
        jobGet:"Job retrieved successfully",
        statusRequired:"Status is required",
        agentRequired:"Agent ID is required",
        agentInvalid:"Invalid AgentId",
        agentProfilesuccess:"Agent profile get succesfully",
        agentNotfound:"Agent not found",
        agentUpdated:"Agent updated successfully",
        agencyGet:"Agency get successfully",
        masterDataget:"Master data get successfully",
        customerGet:"Customer get successfully",
        agencyProfilesuccess:"Agency profile get successfully",
        subjectMessageRequired:"Subject and message are required",
        supportAdded:"Support added successfully",
        supportNotFound:"Support not found",
        supportGet:"Support get successfully",
        supportUpdated:"Support updated successfully",
        supportReply:"Support reply successfully",
        supportDeleted:"Support deleted successfully",
        dashboardGet:"Dashboard get successfully",
        dashboardNotFound:"Dashboard not found",
        customerNotFound:"Customer not found",
        agentGet:"Agent get successfully",
        agentNotFound:"Agent not found",
languageChanged: "Language changed successfully", },

    fr: {
        requiredInput: "Toutes les entrées sont requises",
        invalidEmail: "E-mail invalide",
        invalidPassword: "Mot de passe invalide",
        loginSuccess: "Connexion réussie",
        internalServerError: "Erreur interne du serveur",
        adminProfileSuccess: "Profil administrateur récupéré avec succès",
        invalidUserId: "ID utilisateur manquant ou invalide",
        userNotFound: "Utilisateur non trouvé",
        userUpdated: "Utilisateur mis à jour avec succès",
        oldNewPasswordRequired: "L'ancien et le nouveau mot de passe sont requis",
        newPasswordSame: "Le nouveau mot de passe ne peut pas être identique à l'ancien",
        invalidOldPassword: "Ancien mot de passe invalide",
        passwordChanged: "Mot de passe changé avec succès",
        passwordChangeFailed: "Échec du changement de mot de passe",
        validEmailRequired: "Veuillez entrer un e-mail valide",
        otpError: "Erreur lors de l'envoi de l'OTP",
        otpSent: "OTP envoyé avec succès",
        emailOtpRequired: "E-mail et OTP requis",
        invalidOtp: "OTP invalide ou expiré",
        otpVerified: "OTP vérifié avec succès",
        passwordUpdated: "Mot de passe mis à jour avec succès",
        agentAdded: "Agent ajouté et e-mail envoyé avec succès",
        agencyAdded: "Agence ajoutée avec succès",
        agencyNotFound: "Agence non trouvée",
        agencyUpdated: "Agence mise à jour avec succès",
        agencyDeleted: "Agence supprimée avec succès",
        customerAdded: "Client ajouté avec succès",
        customerUpdated: "Client mis à jour avec succès",
        customerDeleted: "Client supprimé avec succès",
        masterDataAdded: "Données maîtres ajoutées avec succès",
        masterDataNotFound: "Données maîtres non trouvées",
        masterDataUpdated: "Données maîtres mises à jour avec succès",
        masterDataDeleted: "Données maîtres supprimées avec succès",
        languageUpdated: "Langue mise à jour avec succès",
        languageRequired: "La langue est requise",
        jobAdded: "Tâche ajoutée avec succès",
        jobNotFound: "Tâche non trouvée",
        jobUpdated: "Tâche mise à jour avec succès",
        jobget: "Tâche récupérée avec succès",
        getjobDetails: "Détails de la tâche récupérés avec succès",
        jobDeleted: "Tâche supprimée avec succès",
        jobCompleted: "Tâche marquée comme terminée avec succès",
        jobGet: "Tâche obtenue avec succès",
        statusRequired: "Le statut est requis",
        agentRequired: "L'ID de l'agent est requis",
        agentInvalid: "ID de l'agent invalide",
        agentProfilesuccess: "Profil de l'agent récupéré avec succès",
        agentNotfound: "Agent non trouvé",
        agentUpdated: "Agent mis à jour avec succès",
        masterDataget: "Données maîtres récupérées avec succès",
        agencyGet: "Agence récupérée avec succès",
        customerGet: "Client récupéré avec succès",
        agencyProfilesuccess: "Profil de l'agence récupéré avec succès",
        agentGet:"Agent récupéré avec succès",
        subjectMessageRequired:"Le sujet et le message sont requis",
        supportAdded:"Support ajouté avec succès",
        supportNotFound:"Support non trouvé",
        supportGet:"Support récupéré avec succès",
        supportUpdated:"Support mis à jour avec succès",
        supportReply:"Réponse au support réussie",
        supportDeleted:"Support supprimé avec succès",
        dashboardGet:"Tableau de bord récupéré avec succès",
        dashboardNotFound:"Tableau de bord non trouvé",
        customerNotFound:"Client non trouvé",
        languageChanged: "Langue changée avec succès",
    }
};

export default messages;
